/* Generated by re2c 1.0.2 on Thu Dec  6 22:10:10 2018 */
/*
 *  Copyright 2017 by Leander Beernaert (leanderbb@gmail.com)
 *
 *  This file is part of YAL.
 *
 *  YAL is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation, either version 3
 *  of the License, or (at your option) any later version.
 *
 *  YAL is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with YAL. If not, see <http://www.gnu.org/licenses/>.
 */
#include "yal/yal.h"
#include "yal/frontend/lexer/tokens.h"
#include "yal/frontend/lexer/lexer.h"
#define YYMAXFILL 7



namespace yal::frontend {
    // I would really like for YYMAXFILL to be in a header, but it's not possible
    // so we just must make sure that these values are in check
    static_assert(YYMAXFILL == Lexer::kYYMaxFill,
                  "Update Lexer::kYYMaxFile to be of the same value as YYMAXFILL");
    Lexer::Status
    Lexer::re2cExecute() {
        for (;;) {
            m_lexerState.markScanBegin();
            
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	if ((m_lexerState.limit - m_lexerState.current) < 7) if (!m_lexerState.fill(7, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '!':	goto yy11;
	case '&':	goto yy12;
	case '(':	goto yy14;
	case ')':	goto yy16;
	case '*':	goto yy18;
	case '+':	goto yy20;
	case ',':	goto yy22;
	case '-':	goto yy24;
	case '.':	goto yy26;
	case '/':	goto yy28;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy30;
	case ':':	goto yy33;
	case ';':	goto yy35;
	case '<':	goto yy37;
	case '=':	goto yy39;
	case '>':	goto yy41;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'd':
	case 'e':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'p':
	case 'q':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	case '[':	goto yy46;
	case ']':	goto yy48;
	case 'a':	goto yy50;
	case 'b':	goto yy51;
	case 'c':	goto yy52;
	case 'f':	goto yy53;
	case 'i':	goto yy54;
	case 'l':	goto yy55;
	case 'm':	goto yy56;
	case 'n':	goto yy57;
	case 'o':	goto yy58;
	case 'r':	goto yy59;
	case 's':	goto yy60;
	case 't':	goto yy61;
	case 'u':	goto yy62;
	case 'v':	goto yy63;
	case '{':	goto yy64;
	case '}':	goto yy66;
	default:	goto yy4;
	}
yy2:
	++m_lexerState.current;
	{ if (m_lexerState.limit - m_lexerState.token == YYMAXFILL) {return Status::EOS;} }
yy4:
	++m_lexerState.current;
yy5:
	{ setToken(Token::TokenCount, m_lexerState); return Status::Error;}
yy6:
	++m_lexerState.current;
	if (m_lexerState.limit <= m_lexerState.current) if (!m_lexerState.fill(1, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
	{continue;}
yy9:
	++m_lexerState.current;
	{m_lexerState.updateLineStartOffset(); continue;}
yy11:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '=':	goto yy68;
	default:	goto yy5;
	}
yy12:
	++m_lexerState.current;
	{ setToken(Token::Reference, m_lexerState); return Status::Ok;}
yy14:
	++m_lexerState.current;
	{ setToken(Token::BeginPar, m_lexerState); return Status::Ok;}
yy16:
	++m_lexerState.current;
	{ setToken(Token::EndPar, m_lexerState); return Status::Ok;}
yy18:
	++m_lexerState.current;
	{ setToken(Token::Mult, m_lexerState); return Status::Ok;}
yy20:
	++m_lexerState.current;
	{ setToken(Token::Plus, m_lexerState); return Status::Ok;}
yy22:
	++m_lexerState.current;
	{ setToken(Token::Comma, m_lexerState); return Status::Ok;}
yy24:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy25;
	}
yy25:
	{ setToken(Token::Minus, m_lexerState); return Status::Ok;}
yy26:
	++m_lexerState.current;
	{ setToken(Token::Dot, m_lexerState); return Status::Ok;}
yy28:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '/':	goto yy72;
	default:	goto yy29;
	}
yy29:
	{ setToken(Token::Div, m_lexerState); return Status::Ok;}
yy30:
	yyaccept = 0;
	m_lexerState.marker = ++m_lexerState.current;
	if ((m_lexerState.limit - m_lexerState.current) < 3) if (!m_lexerState.fill(3, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '.':	goto yy74;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy30;
	case 'i':	goto yy76;
	case 'u':	goto yy77;
	default:	goto yy32;
	}
yy32:
	{ setToken(Token::IntegerLiteral, m_lexerState); return Status::Ok;}
yy33:
	++m_lexerState.current;
	{ setToken(Token::Colon, m_lexerState); return Status::Ok;}
yy35:
	++m_lexerState.current;
	{ setToken(Token::SemiColon, m_lexerState); return Status::Ok;}
yy37:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '=':	goto yy78;
	default:	goto yy38;
	}
yy38:
	{ setToken(Token::CompareLt, m_lexerState); return Status::Ok;}
yy39:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '=':	goto yy80;
	default:	goto yy40;
	}
yy40:
	{ setToken(Token::Assign, m_lexerState); return Status::Ok;}
yy41:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '=':	goto yy82;
	default:	goto yy42;
	}
yy42:
	{ setToken(Token::CompareGt, m_lexerState); return Status::Ok;}
yy43:
	yyaccept = 1;
	m_lexerState.marker = ++m_lexerState.current;
	if (m_lexerState.limit <= m_lexerState.current) if (!m_lexerState.fill(1, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
yy44:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	case ':':	goto yy84;
	default:	goto yy45;
	}
yy45:
	{ setToken(Token::Identifier, m_lexerState); return Status::Ok;}
yy46:
	++m_lexerState.current;
	{ setToken(Token::BeginArray, m_lexerState); return Status::Ok;}
yy48:
	++m_lexerState.current;
	{ setToken(Token::EndArray, m_lexerState); return Status::Ok;}
yy50:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'l':	goto yy85;
	case 'n':	goto yy86;
	case 's':	goto yy87;
	default:	goto yy44;
	}
yy51:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'o':	goto yy89;
	default:	goto yy44;
	}
yy52:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'a':	goto yy90;
	default:	goto yy44;
	}
yy53:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '3':	goto yy91;
	case '6':	goto yy92;
	case 'a':	goto yy93;
	case 'n':	goto yy94;
	case 'r':	goto yy96;
	default:	goto yy44;
	}
yy54:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '1':	goto yy97;
	case '3':	goto yy98;
	case '8':	goto yy99;
	case 'm':	goto yy101;
	default:	goto yy44;
	}
yy55:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'e':	goto yy102;
	default:	goto yy44;
	}
yy56:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'o':	goto yy103;
	case 'u':	goto yy104;
	default:	goto yy44;
	}
yy57:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'o':	goto yy105;
	default:	goto yy44;
	}
yy58:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'r':	goto yy106;
	default:	goto yy44;
	}
yy59:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'e':	goto yy108;
	default:	goto yy44;
	}
yy60:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'e':	goto yy109;
	case 't':	goto yy110;
	default:	goto yy44;
	}
yy61:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'h':	goto yy111;
	case 'r':	goto yy112;
	case 'y':	goto yy113;
	default:	goto yy44;
	}
yy62:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '1':	goto yy114;
	case '3':	goto yy115;
	case '8':	goto yy116;
	default:	goto yy44;
	}
yy63:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'a':	goto yy118;
	default:	goto yy44;
	}
yy64:
	++m_lexerState.current;
	{ setToken(Token::BeginScope, m_lexerState); return Status::Ok;}
yy66:
	++m_lexerState.current;
	{ setToken(Token::EndScope, m_lexerState); return Status::Ok;}
yy68:
	++m_lexerState.current;
	{ setToken(Token::CompareNe, m_lexerState); return Status::Ok;}
yy70:
	yyaccept = 0;
	m_lexerState.marker = ++m_lexerState.current;
	if ((m_lexerState.limit - m_lexerState.current) < 3) if (!m_lexerState.fill(3, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	case 'i':	goto yy76;
	case 'u':	goto yy77;
	default:	goto yy32;
	}
yy72:
	++m_lexerState.current;
	if (m_lexerState.limit <= m_lexerState.current) if (!m_lexerState.fill(1, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '\n':	goto yy119;
	default:	goto yy72;
	}
yy74:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy121;
	default:	goto yy75;
	}
yy75:
	m_lexerState.current = m_lexerState.marker;
	switch (yyaccept) {
	case 0: 	goto yy32;
	case 1: 	goto yy45;
	case 2: 	goto yy88;
	case 3: 	goto yy95;
	case 4: 	goto yy100;
	case 5: 	goto yy107;
	case 6: 	goto yy117;
	case 7: 	goto yy123;
	case 8: 	goto yy135;
	case 9: 	goto yy139;
	case 10: 	goto yy141;
	case 11: 	goto yy145;
	case 12: 	goto yy147;
	case 13: 	goto yy150;
	case 14: 	goto yy152;
	case 15: 	goto yy154;
	case 16: 	goto yy156;
	case 17: 	goto yy164;
	case 18: 	goto yy166;
	case 19: 	goto yy168;
	case 20: 	goto yy180;
	case 21: 	goto yy183;
	case 22: 	goto yy185;
	case 23: 	goto yy188;
	case 24: 	goto yy190;
	case 25: 	goto yy194;
	case 26: 	goto yy197;
	case 27: 	goto yy199;
	case 28: 	goto yy201;
	case 29: 	goto yy205;
	case 30: 	goto yy207;
	case 31: 	goto yy216;
	case 32: 	goto yy218;
	default:	goto yy220;
	}
yy76:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '1':	goto yy124;
	case '3':	goto yy125;
	case '8':	goto yy126;
	default:	goto yy75;
	}
yy77:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '1':	goto yy128;
	case '3':	goto yy129;
	case '8':	goto yy130;
	default:	goto yy75;
	}
yy78:
	++m_lexerState.current;
	{ setToken(Token::CompareLe, m_lexerState); return Status::Ok;}
yy80:
	++m_lexerState.current;
	{ setToken(Token::CompareEq, m_lexerState); return Status::Ok;}
yy82:
	++m_lexerState.current;
	{ setToken(Token::CompareGe, m_lexerState); return Status::Ok;}
yy84:
	++m_lexerState.current;
	if (m_lexerState.limit <= m_lexerState.current) if (!m_lexerState.fill(1, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case ':':	goto yy132;
	default:	goto yy75;
	}
yy85:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'i':	goto yy133;
	default:	goto yy44;
	}
yy86:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'd':	goto yy134;
	default:	goto yy44;
	}
yy87:
	yyaccept = 2;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy88;
	}
yy88:
	{ setToken(Token::As, m_lexerState);return Status::Ok; }
yy89:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'o':	goto yy136;
	default:	goto yy44;
	}
yy90:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 's':	goto yy137;
	default:	goto yy44;
	}
yy91:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '2':	goto yy138;
	default:	goto yy44;
	}
yy92:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '4':	goto yy140;
	default:	goto yy44;
	}
yy93:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'l':	goto yy142;
	default:	goto yy44;
	}
yy94:
	yyaccept = 3;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy95;
	}
yy95:
	{ setToken(Token::Function, m_lexerState);return Status::Ok; }
yy96:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'o':	goto yy143;
	default:	goto yy44;
	}
yy97:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '6':	goto yy144;
	default:	goto yy44;
	}
yy98:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '2':	goto yy146;
	default:	goto yy44;
	}
yy99:
	yyaccept = 4;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy100;
	}
yy100:
	{ setToken(Token::TypeInt8, m_lexerState); return Status::Ok;}
yy101:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'p':	goto yy148;
	default:	goto yy44;
	}
yy102:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 't':	goto yy149;
	default:	goto yy44;
	}
yy103:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'd':	goto yy151;
	default:	goto yy44;
	}
yy104:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 't':	goto yy153;
	default:	goto yy44;
	}
yy105:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 't':	goto yy155;
	default:	goto yy44;
	}
yy106:
	yyaccept = 5;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy107;
	}
yy107:
	{ setToken(Token::Or, m_lexerState); return Status::Ok; }
yy108:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 't':	goto yy157;
	default:	goto yy44;
	}
yy109:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'l':	goto yy158;
	default:	goto yy44;
	}
yy110:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'r':	goto yy159;
	default:	goto yy44;
	}
yy111:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'i':	goto yy160;
	default:	goto yy44;
	}
yy112:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'u':	goto yy161;
	default:	goto yy44;
	}
yy113:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'p':	goto yy162;
	default:	goto yy44;
	}
yy114:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '6':	goto yy163;
	default:	goto yy44;
	}
yy115:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '2':	goto yy165;
	default:	goto yy44;
	}
yy116:
	yyaccept = 6;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy117;
	}
yy117:
	{ setToken(Token::TypeUInt8, m_lexerState); return Status::Ok;}
yy118:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'r':	goto yy167;
	default:	goto yy44;
	}
yy119:
	++m_lexerState.current;
	{m_lexerState.updateLineStartOffset();continue;}
yy121:
	yyaccept = 7;
	m_lexerState.marker = ++m_lexerState.current;
	if ((m_lexerState.limit - m_lexerState.current) < 3) if (!m_lexerState.fill(3, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy121;
	case 'f':	goto yy169;
	default:	goto yy123;
	}
yy123:
	{ setToken(Token::DecimalLiteral, m_lexerState); return Status::Ok;}
yy124:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '6':	goto yy170;
	default:	goto yy75;
	}
yy125:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '2':	goto yy172;
	default:	goto yy75;
	}
yy126:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralI8, m_lexerState); return Status::Ok;}
yy128:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '6':	goto yy174;
	default:	goto yy75;
	}
yy129:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '2':	goto yy176;
	default:	goto yy75;
	}
yy130:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralU8, m_lexerState); return Status::Ok;}
yy132:
	++m_lexerState.current;
	if (m_lexerState.limit <= m_lexerState.current) if (!m_lexerState.fill(1, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy178;
	default:	goto yy75;
	}
yy133:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'a':	goto yy181;
	default:	goto yy44;
	}
yy134:
	yyaccept = 8;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy135;
	}
yy135:
	{ setToken(Token::And, m_lexerState); return Status::Ok; }
yy136:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'l':	goto yy182;
	default:	goto yy44;
	}
yy137:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 't':	goto yy184;
	default:	goto yy44;
	}
yy138:
	yyaccept = 9;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy139;
	}
yy139:
	{ setToken(Token::TypeFloat32, m_lexerState); return Status::Ok;}
yy140:
	yyaccept = 10;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy141;
	}
yy141:
	{ setToken(Token::TypeFloat64, m_lexerState); return Status::Ok;}
yy142:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 's':	goto yy186;
	default:	goto yy44;
	}
yy143:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'm':	goto yy187;
	default:	goto yy44;
	}
yy144:
	yyaccept = 11;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy145;
	}
yy145:
	{ setToken(Token::TypeInt16, m_lexerState); return Status::Ok;}
yy146:
	yyaccept = 12;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy147;
	}
yy147:
	{ setToken(Token::TypeInt32, m_lexerState); return Status::Ok;}
yy148:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'l':	goto yy189;
	case 'o':	goto yy191;
	default:	goto yy44;
	}
yy149:
	yyaccept = 13;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy150;
	}
yy150:
	{ setToken(Token::Let, m_lexerState);return Status::Ok; }
yy151:
	yyaccept = 14;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy152;
	}
yy152:
	{ setToken(Token::Mod, m_lexerState); return Status::Ok;}
yy153:
	yyaccept = 15;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy154;
	}
yy154:
	{ setToken(Token::Mutable, m_lexerState); return Status::Ok;}
yy155:
	yyaccept = 16;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy156;
	}
yy156:
	{ setToken(Token::Not, m_lexerState); return Status::Ok; }
yy157:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'u':	goto yy192;
	default:	goto yy44;
	}
yy158:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'f':	goto yy193;
	default:	goto yy44;
	}
yy159:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'u':	goto yy195;
	default:	goto yy44;
	}
yy160:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 's':	goto yy196;
	default:	goto yy44;
	}
yy161:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'e':	goto yy198;
	default:	goto yy44;
	}
yy162:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'e':	goto yy200;
	default:	goto yy44;
	}
yy163:
	yyaccept = 17;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy164;
	}
yy164:
	{ setToken(Token::TypeUInt16, m_lexerState); return Status::Ok;}
yy165:
	yyaccept = 18;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy166;
	}
yy166:
	{ setToken(Token::TypeUInt32, m_lexerState); return Status::Ok;}
yy167:
	yyaccept = 19;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy168;
	}
yy168:
	{ setToken(Token::Var, m_lexerState); return Status::Ok; }
yy169:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '3':	goto yy202;
	case '6':	goto yy203;
	default:	goto yy75;
	}
yy170:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralI16, m_lexerState); return Status::Ok;}
yy172:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralI32, m_lexerState); return Status::Ok;}
yy174:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralU16, m_lexerState); return Status::Ok;}
yy176:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralU32, m_lexerState); return Status::Ok;}
yy178:
	yyaccept = 20;
	m_lexerState.marker = ++m_lexerState.current;
	if (m_lexerState.limit <= m_lexerState.current) if (!m_lexerState.fill(1, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy178;
	case ':':	goto yy84;
	default:	goto yy180;
	}
yy180:
	{setToken(Token::IdentifierMulti, m_lexerState); return Status::Ok;}
yy181:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 's':	goto yy204;
	default:	goto yy44;
	}
yy182:
	yyaccept = 21;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy183;
	}
yy183:
	{ setToken(Token::TypeBool, m_lexerState); return Status::Ok;}
yy184:
	yyaccept = 22;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy185;
	}
yy185:
	{ setToken(Token::Cast, m_lexerState);return Status::Ok; }
yy186:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'e':	goto yy206;
	default:	goto yy44;
	}
yy187:
	yyaccept = 23;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy188;
	}
yy188:
	{ setToken(Token::From, m_lexerState); return Status::Ok;}
yy189:
	yyaccept = 24;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy190;
	}
yy190:
	{ setToken(Token::Impl, m_lexerState); return Status::Ok;}
yy191:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'r':	goto yy208;
	default:	goto yy44;
	}
yy192:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'r':	goto yy209;
	default:	goto yy44;
	}
yy193:
	yyaccept = 25;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy194;
	}
yy194:
	{ setToken(Token::Self, m_lexerState);return Status::Ok; }
yy195:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'c':	goto yy210;
	default:	goto yy44;
	}
yy196:
	yyaccept = 26;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy197;
	}
yy197:
	{ setToken(Token::This, m_lexerState);return Status::Ok; }
yy198:
	yyaccept = 27;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy199;
	}
yy199:
	{ setToken(Token::True, m_lexerState); return Status::Ok; }
yy200:
	yyaccept = 28;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy201;
	}
yy201:
	{ setToken(Token::Type, m_lexerState); return Status::Ok;}
yy202:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '2':	goto yy211;
	default:	goto yy75;
	}
yy203:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '4':	goto yy213;
	default:	goto yy75;
	}
yy204:
	yyaccept = 29;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy205;
	}
yy205:
	{ setToken(Token::Alias, m_lexerState); return Status::Ok;}
yy206:
	yyaccept = 30;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy207;
	}
yy207:
	{ setToken(Token::False, m_lexerState); return Status::Ok; }
yy208:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 't':	goto yy215;
	default:	goto yy44;
	}
yy209:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 'n':	goto yy217;
	default:	goto yy44;
	}
yy210:
	yyaccept = 1;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case 't':	goto yy219;
	default:	goto yy44;
	}
yy211:
	++m_lexerState.current;
	{ setToken(Token::DecimalLiteral32, m_lexerState); return Status::Ok;}
yy213:
	++m_lexerState.current;
	{ setToken(Token::DecimalLiteral64, m_lexerState); return Status::Ok;}
yy215:
	yyaccept = 31;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy216;
	}
yy216:
	{ setToken(Token::Import, m_lexerState);return Status::Ok; }
yy217:
	yyaccept = 32;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy218;
	}
yy218:
	{ setToken(Token::Return, m_lexerState);return Status::Ok; }
yy219:
	yyaccept = 33;
	yych = *(m_lexerState.marker = ++m_lexerState.current);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy44;
	default:	goto yy220;
	}
yy220:
	{ setToken(Token::Struct, m_lexerState); return Status::Ok;}
}

        }

    }
}
