/* Generated by re2c 1.0.2 on Thu Jun 14 09:05:12 2018 */
/*
 *  Copyright 2017 by Leander Beernaert (leanderbb@gmail.com)
 *
 *  This file is part of YAL.
 *
 *  YAL is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation, either version 3
 *  of the License, or (at your option) any later version.
 *
 *  YAL is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with YAL. If not, see <http://www.gnu.org/licenses/>.
 */
#include "yal/yal.h"
#include "yal/frontend/lexer/tokens.h"
#include "yal/frontend/lexer/lexer.h"
#define YYMAXFILL 11



namespace yal::frontend {
    // I would really like for YYMAXFILL to be in a header, but it's not possible
    // so we just must make sure that these values are in check
    static_assert(YYMAXFILL == Lexer::kYYMaxFill,
                  "Update Lexer::kYYMaxFile to be of the same value as YYMAXFILL");
    Lexer::Status
    Lexer::re2cExecute() {
        for (;;) {
            m_lexerState.markScanBegin();
            
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	if ((m_lexerState.limit - m_lexerState.current) < 11) if (!m_lexerState.fill(11, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case ' ':	goto yy6;
	case '\n':	goto yy9;
	case '!':	goto yy11;
	case '&':	goto yy12;
	case '(':	goto yy14;
	case ')':	goto yy16;
	case '*':	goto yy18;
	case '+':	goto yy20;
	case ',':	goto yy22;
	case '-':	goto yy24;
	case '.':	goto yy26;
	case '/':	goto yy28;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy30;
	case ':':	goto yy33;
	case ';':	goto yy35;
	case '<':	goto yy37;
	case '=':	goto yy39;
	case '>':	goto yy41;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'd':
	case 'e':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'p':
	case 'q':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	case '[':	goto yy46;
	case ']':	goto yy48;
	case 'a':	goto yy50;
	case 'b':	goto yy51;
	case 'c':	goto yy52;
	case 'f':	goto yy53;
	case 'i':	goto yy54;
	case 'l':	goto yy55;
	case 'm':	goto yy56;
	case 'n':	goto yy57;
	case 'o':	goto yy58;
	case 'r':	goto yy59;
	case 's':	goto yy60;
	case 't':	goto yy61;
	case 'u':	goto yy62;
	case 'v':	goto yy63;
	case '{':	goto yy64;
	case '}':	goto yy66;
	default:	goto yy4;
	}
yy2:
	++m_lexerState.current;
	{ if (m_lexerState.limit - m_lexerState.token == YYMAXFILL) {return Status::EOS;} }
yy4:
	++m_lexerState.current;
yy5:
	{ setToken(Token::TokenCount, m_lexerState); return Status::Error;}
yy6:
	++m_lexerState.current;
	if (m_lexerState.limit <= m_lexerState.current) if (!m_lexerState.fill(1, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
	{continue;}
yy9:
	++m_lexerState.current;
	{m_lexerState.updateLineStartOffset(); continue;}
yy11:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '=':	goto yy68;
	default:	goto yy5;
	}
yy12:
	++m_lexerState.current;
	{ setToken(Token::Reference, m_lexerState); return Status::Ok;}
yy14:
	++m_lexerState.current;
	{ setToken(Token::BeginPar, m_lexerState); return Status::Ok;}
yy16:
	++m_lexerState.current;
	{ setToken(Token::EndPar, m_lexerState); return Status::Ok;}
yy18:
	++m_lexerState.current;
	{ setToken(Token::Mult, m_lexerState); return Status::Ok;}
yy20:
	++m_lexerState.current;
	{ setToken(Token::Plus, m_lexerState); return Status::Ok;}
yy22:
	++m_lexerState.current;
	{ setToken(Token::Comma, m_lexerState); return Status::Ok;}
yy24:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy25;
	}
yy25:
	{ setToken(Token::Minus, m_lexerState); return Status::Ok;}
yy26:
	++m_lexerState.current;
	{ setToken(Token::Dot, m_lexerState); return Status::Ok;}
yy28:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '/':	goto yy72;
	default:	goto yy29;
	}
yy29:
	{ setToken(Token::Div, m_lexerState); return Status::Ok;}
yy30:
	yyaccept = 0;
	m_lexerState.marker = ++m_lexerState.current;
	if ((m_lexerState.limit - m_lexerState.current) < 3) if (!m_lexerState.fill(3, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '.':	goto yy74;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy30;
	case 'i':	goto yy76;
	case 'u':	goto yy77;
	default:	goto yy32;
	}
yy32:
	{ setToken(Token::IntegerLiteral, m_lexerState); return Status::Ok;}
yy33:
	++m_lexerState.current;
	{ setToken(Token::Colon, m_lexerState); return Status::Ok;}
yy35:
	++m_lexerState.current;
	{ setToken(Token::SemiColon, m_lexerState); return Status::Ok;}
yy37:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '=':	goto yy78;
	default:	goto yy38;
	}
yy38:
	{ setToken(Token::CompareLt, m_lexerState); return Status::Ok;}
yy39:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '=':	goto yy80;
	default:	goto yy40;
	}
yy40:
	{ setToken(Token::Assign, m_lexerState); return Status::Ok;}
yy41:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '=':	goto yy82;
	default:	goto yy42;
	}
yy42:
	{ setToken(Token::CompareGt, m_lexerState); return Status::Ok;}
yy43:
	++m_lexerState.current;
	if (m_lexerState.limit <= m_lexerState.current) if (!m_lexerState.fill(1, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
yy44:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy45;
	}
yy45:
	{ setToken(Token::Identifier, m_lexerState); return Status::Ok;}
yy46:
	++m_lexerState.current;
	{ setToken(Token::BeginArray, m_lexerState); return Status::Ok;}
yy48:
	++m_lexerState.current;
	{ setToken(Token::EndArray, m_lexerState); return Status::Ok;}
yy50:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'n':	goto yy84;
	default:	goto yy44;
	}
yy51:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'o':	goto yy85;
	default:	goto yy44;
	}
yy52:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'a':	goto yy86;
	default:	goto yy44;
	}
yy53:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '3':	goto yy87;
	case '6':	goto yy88;
	case 'a':	goto yy89;
	case 'n':	goto yy90;
	default:	goto yy44;
	}
yy54:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '1':	goto yy92;
	case '3':	goto yy93;
	case '8':	goto yy94;
	default:	goto yy44;
	}
yy55:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'e':	goto yy96;
	default:	goto yy44;
	}
yy56:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'o':	goto yy97;
	case 'u':	goto yy98;
	default:	goto yy44;
	}
yy57:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'o':	goto yy99;
	default:	goto yy44;
	}
yy58:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'r':	goto yy100;
	default:	goto yy44;
	}
yy59:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'a':	goto yy102;
	case 'e':	goto yy103;
	default:	goto yy44;
	}
yy60:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'e':	goto yy104;
	case 't':	goto yy105;
	default:	goto yy44;
	}
yy61:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'h':	goto yy106;
	case 'r':	goto yy107;
	case 'y':	goto yy108;
	default:	goto yy44;
	}
yy62:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '1':	goto yy109;
	case '3':	goto yy110;
	case '8':	goto yy111;
	default:	goto yy44;
	}
yy63:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'a':	goto yy113;
	default:	goto yy44;
	}
yy64:
	++m_lexerState.current;
	{ setToken(Token::BeginScope, m_lexerState); return Status::Ok;}
yy66:
	++m_lexerState.current;
	{ setToken(Token::EndScope, m_lexerState); return Status::Ok;}
yy68:
	++m_lexerState.current;
	{ setToken(Token::CompareNe, m_lexerState); return Status::Ok;}
yy70:
	yyaccept = 0;
	m_lexerState.marker = ++m_lexerState.current;
	if ((m_lexerState.limit - m_lexerState.current) < 3) if (!m_lexerState.fill(3, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	case 'i':	goto yy76;
	case 'u':	goto yy77;
	default:	goto yy32;
	}
yy72:
	++m_lexerState.current;
	if (m_lexerState.limit <= m_lexerState.current) if (!m_lexerState.fill(1, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '\n':	goto yy114;
	default:	goto yy72;
	}
yy74:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy116;
	default:	goto yy75;
	}
yy75:
	m_lexerState.current = m_lexerState.marker;
	if (yyaccept == 0) {
		goto yy32;
	} else {
		goto yy118;
	}
yy76:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '1':	goto yy119;
	case '3':	goto yy120;
	case '8':	goto yy121;
	default:	goto yy75;
	}
yy77:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '1':	goto yy123;
	case '3':	goto yy124;
	case '8':	goto yy125;
	default:	goto yy75;
	}
yy78:
	++m_lexerState.current;
	{ setToken(Token::CompareLe, m_lexerState); return Status::Ok;}
yy80:
	++m_lexerState.current;
	{ setToken(Token::CompareEq, m_lexerState); return Status::Ok;}
yy82:
	++m_lexerState.current;
	{ setToken(Token::CompareGe, m_lexerState); return Status::Ok;}
yy84:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'd':	goto yy127;
	default:	goto yy44;
	}
yy85:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'o':	goto yy129;
	default:	goto yy44;
	}
yy86:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 's':	goto yy130;
	default:	goto yy44;
	}
yy87:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '2':	goto yy131;
	default:	goto yy44;
	}
yy88:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '4':	goto yy133;
	default:	goto yy44;
	}
yy89:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'l':	goto yy135;
	default:	goto yy44;
	}
yy90:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy91;
	}
yy91:
	{ setToken(Token::Function, m_lexerState);return Status::Ok; }
yy92:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '6':	goto yy136;
	default:	goto yy44;
	}
yy93:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '2':	goto yy138;
	default:	goto yy44;
	}
yy94:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy95;
	}
yy95:
	{ setToken(Token::TypeInt8, m_lexerState); return Status::Ok;}
yy96:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 't':	goto yy140;
	default:	goto yy44;
	}
yy97:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'd':	goto yy142;
	default:	goto yy44;
	}
yy98:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 't':	goto yy144;
	default:	goto yy44;
	}
yy99:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 't':	goto yy146;
	default:	goto yy44;
	}
yy100:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy101;
	}
yy101:
	{ setToken(Token::Or, m_lexerState); return Status::Ok; }
yy102:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'n':	goto yy148;
	default:	goto yy44;
	}
yy103:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 't':	goto yy149;
	default:	goto yy44;
	}
yy104:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'l':	goto yy150;
	default:	goto yy44;
	}
yy105:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'r':	goto yy151;
	default:	goto yy44;
	}
yy106:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'i':	goto yy152;
	default:	goto yy44;
	}
yy107:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'u':	goto yy153;
	default:	goto yy44;
	}
yy108:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'p':	goto yy154;
	default:	goto yy44;
	}
yy109:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '6':	goto yy155;
	default:	goto yy44;
	}
yy110:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '2':	goto yy157;
	default:	goto yy44;
	}
yy111:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy112;
	}
yy112:
	{ setToken(Token::TypeUInt8, m_lexerState); return Status::Ok;}
yy113:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'r':	goto yy159;
	default:	goto yy44;
	}
yy114:
	++m_lexerState.current;
	{m_lexerState.updateLineStartOffset();continue;}
yy116:
	yyaccept = 1;
	m_lexerState.marker = ++m_lexerState.current;
	if ((m_lexerState.limit - m_lexerState.current) < 3) if (!m_lexerState.fill(3, m_stream)) return Status::EOS;
	yych = *m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy116;
	case 'f':	goto yy161;
	default:	goto yy118;
	}
yy118:
	{ setToken(Token::DecimalLiteral, m_lexerState); return Status::Ok;}
yy119:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '6':	goto yy162;
	default:	goto yy75;
	}
yy120:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '2':	goto yy164;
	default:	goto yy75;
	}
yy121:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralI8, m_lexerState); return Status::Ok;}
yy123:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '6':	goto yy166;
	default:	goto yy75;
	}
yy124:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '2':	goto yy168;
	default:	goto yy75;
	}
yy125:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralU8, m_lexerState); return Status::Ok;}
yy127:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy128;
	}
yy128:
	{ setToken(Token::And, m_lexerState); return Status::Ok; }
yy129:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'l':	goto yy170;
	default:	goto yy44;
	}
yy130:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 't':	goto yy172;
	default:	goto yy44;
	}
yy131:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy132;
	}
yy132:
	{ setToken(Token::TypeFloat32, m_lexerState); return Status::Ok;}
yy133:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy134;
	}
yy134:
	{ setToken(Token::TypeFloat64, m_lexerState); return Status::Ok;}
yy135:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 's':	goto yy174;
	default:	goto yy44;
	}
yy136:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy137;
	}
yy137:
	{ setToken(Token::TypeInt16, m_lexerState); return Status::Ok;}
yy138:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy139;
	}
yy139:
	{ setToken(Token::TypeInt32, m_lexerState); return Status::Ok;}
yy140:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy141;
	}
yy141:
	{ setToken(Token::Let, m_lexerState);return Status::Ok; }
yy142:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy143;
	}
yy143:
	{ setToken(Token::Mod, m_lexerState); return Status::Ok;}
yy144:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy145;
	}
yy145:
	{ setToken(Token::Mutable, m_lexerState); return Status::Ok;}
yy146:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy147;
	}
yy147:
	{ setToken(Token::Not, m_lexerState); return Status::Ok; }
yy148:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'g':	goto yy175;
	default:	goto yy44;
	}
yy149:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'u':	goto yy176;
	default:	goto yy44;
	}
yy150:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'f':	goto yy177;
	default:	goto yy44;
	}
yy151:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'u':	goto yy179;
	default:	goto yy44;
	}
yy152:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 's':	goto yy180;
	default:	goto yy44;
	}
yy153:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'e':	goto yy182;
	default:	goto yy44;
	}
yy154:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'e':	goto yy184;
	default:	goto yy44;
	}
yy155:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy156;
	}
yy156:
	{ setToken(Token::TypeUInt16, m_lexerState); return Status::Ok;}
yy157:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy158;
	}
yy158:
	{ setToken(Token::TypeUInt32, m_lexerState); return Status::Ok;}
yy159:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy160;
	}
yy160:
	{ setToken(Token::Var, m_lexerState); return Status::Ok; }
yy161:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '3':	goto yy186;
	case '6':	goto yy187;
	default:	goto yy75;
	}
yy162:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralI16, m_lexerState); return Status::Ok;}
yy164:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralI32, m_lexerState); return Status::Ok;}
yy166:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralU16, m_lexerState); return Status::Ok;}
yy168:
	++m_lexerState.current;
	{ setToken(Token::IntegerLiteralU32, m_lexerState); return Status::Ok;}
yy170:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy171;
	}
yy171:
	{ setToken(Token::TypeBool, m_lexerState); return Status::Ok;}
yy172:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy173;
	}
yy173:
	{ setToken(Token::Cast, m_lexerState);return Status::Ok; }
yy174:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'e':	goto yy188;
	default:	goto yy44;
	}
yy175:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'e':	goto yy190;
	default:	goto yy44;
	}
yy176:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'r':	goto yy191;
	default:	goto yy44;
	}
yy177:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy178;
	}
yy178:
	{ setToken(Token::Self, m_lexerState);return Status::Ok; }
yy179:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'c':	goto yy192;
	default:	goto yy44;
	}
yy180:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy181;
	}
yy181:
	{ setToken(Token::This, m_lexerState);return Status::Ok; }
yy182:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy183;
	}
yy183:
	{ setToken(Token::True, m_lexerState); return Status::Ok; }
yy184:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy185;
	}
yy185:
	{ setToken(Token::Type, m_lexerState); return Status::Ok;}
yy186:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '2':	goto yy193;
	default:	goto yy75;
	}
yy187:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '4':	goto yy195;
	default:	goto yy75;
	}
yy188:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy189;
	}
yy189:
	{ setToken(Token::False, m_lexerState); return Status::Ok; }
yy190:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '_':	goto yy197;
	default:	goto yy44;
	}
yy191:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'n':	goto yy198;
	default:	goto yy44;
	}
yy192:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 't':	goto yy200;
	default:	goto yy44;
	}
yy193:
	++m_lexerState.current;
	{ setToken(Token::DecimalLiteral32, m_lexerState); return Status::Ok;}
yy195:
	++m_lexerState.current;
	{ setToken(Token::DecimalLiteral64, m_lexerState); return Status::Ok;}
yy197:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'c':	goto yy202;
	default:	goto yy44;
	}
yy198:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy199;
	}
yy199:
	{ setToken(Token::Return, m_lexerState);return Status::Ok; }
yy200:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy201;
	}
yy201:
	{ setToken(Token::Struct, m_lexerState); return Status::Ok;}
yy202:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 'a':	goto yy203;
	default:	goto yy44;
	}
yy203:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 's':	goto yy204;
	default:	goto yy44;
	}
yy204:
	yych = *++m_lexerState.current;
	switch (yych) {
	case 't':	goto yy205;
	default:	goto yy44;
	}
yy205:
	yych = *++m_lexerState.current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy206;
	}
yy206:
	{ setToken(Token::RangeCast, m_lexerState);return Status::Ok; }
}

        }

    }
}
