/*
 * Define the YAL_NODE_LIST_FUNC_MACRO(x) to use this on the list
 */
YAL_NODE_LIST_FUNC(VariableDeclNode)
YAL_NODE_LIST_FUNC(FunctionDeclNode)
YAL_NODE_LIST_FUNC(ConditionNode)
YAL_NODE_LIST_FUNC(SingleOperatorNode)
YAL_NODE_LIST_FUNC(DualOperatorNode)
YAL_NODE_LIST_FUNC(CompareOperatorNode)
YAL_NODE_LIST_FUNC(AssignOperatorNode)
YAL_NODE_LIST_FUNC(ReturnNode)
YAL_NODE_LIST_FUNC(CodeBodyNode)
YAL_NODE_LIST_FUNC(ArgumentDeclNode)
YAL_NODE_LIST_FUNC(ArgumentDeclsNode)
YAL_NODE_LIST_FUNC(FunctionCallArgsNode)
YAL_NODE_LIST_FUNC(ConstantNode)
YAL_NODE_LIST_FUNC(FunctionCallNode)
YAL_NODE_LIST_FUNC(PrintNode)
YAL_NODE_LIST_FUNC(PrintArgsNode)
