#pragma once

namespace yal
{
    enum class Token
    {
        Var,
        Let,
        True,
        False,
        If,
        Elif,
        Else,
        And,
        Or,
        Not,
        Return,
        Function,
        While,
        For,
        TypeBool,
        TypeInt32,
        TypeUInt32,
        TypeFlaot,
        TypeDouble,
        TypeString,
        This,
        Mod,
        Dot,
        BeginArray,
        EndArray,
        BeginScope,
        EndScope,
        ShiftRight,
        ShiftLeft,
        BitXor,
        BitTil,
        BitOr,
        CompareGe,
        CompareGt,
        CompareLe,
        CompareLt,
        CompareEq,
        CompareNe,
        Assign,
        AssignPlus,
        AssignMinus,
        AssignMult,
        AssignDiv,
        AssignAnd,
        AssignOr,
        AssignXor,
        AssignShiftRight,
        AssignShiftLeft,
        Plus,
        Minus,
        Mult,
        Div,
        TokenCount
    };

    const char* TokenToString(const Token token);
}
